// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneCompany.Infrastructure;

#nullable disable

namespace PhoneCompany.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneCompanyDbContext))]
    [Migration("20250505212928_RemoveUserIdFromRefreshTokenTable")]
    partial class RemoveUserIdFromRefreshTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PhoneNumberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CustomerEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Inactive");

                    b.Property<Guid?>("TariffPalnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("TariffPalnId");

                    b.ToTable("PhoneNumberEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokenEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("RoleEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("real")
                        .HasAnnotation("CheckConstraint", "Price >= 0");

                    b.HasKey("Id");

                    b.ToTable("ServiceEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.TariffPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("real")
                        .HasAnnotation("CheckConstraint", "Price >= 0");

                    b.HasKey("Id");

                    b.ToTable("TariffPlanEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.TariffPlanServiceEntity", b =>
                {
                    b.Property<Guid>("TariffPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("TariffPlanId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TariffPlanServiceEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("PhoneCompany.Infrastructure.Entities.CustomerEntity", "Customer")
                        .WithOne("PhoneNumber")
                        .HasForeignKey("PhoneCompany.Infrastructure.Entities.PhoneNumberEntity", "CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhoneCompany.Infrastructure.Entities.TariffPlanEntity", "TariffPlan")
                        .WithMany("Numbers")
                        .HasForeignKey("TariffPalnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("TariffPlan");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("PhoneCompany.Infrastructure.Entities.UserEntity", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("PhoneCompany.Infrastructure.Entities.RefreshTokenEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.TariffPlanServiceEntity", b =>
                {
                    b.HasOne("PhoneCompany.Infrastructure.Entities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoneCompany.Infrastructure.Entities.TariffPlanEntity", null)
                        .WithMany()
                        .HasForeignKey("TariffPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.UserEntity", b =>
                {
                    b.HasOne("PhoneCompany.Infrastructure.Entities.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.CustomerEntity", b =>
                {
                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.TariffPlanEntity", b =>
                {
                    b.Navigation("Numbers");
                });

            modelBuilder.Entity("PhoneCompany.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
